name: vue-template
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install and Build
      run: |
        npm install
        npm run build
          
    - name: Log in to Docker Hub #登陆docker
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  #docker的用户名
        password: ${{ secrets.DOCKER_PASSWORD }}	#docker的密码

    - name: Extract metadata (tags, labels) for Docker # 获取元数据包括tag和labels
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: herzorf/vite-project

    - name: Build and push Docker image  #构建和发布 docker镜像
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}  #上一步所拿到的tags，默认是分支名字
        labels: ${{ steps.meta.outputs.labels }} # 上一步所拿到的labels
